d/control: qemu 6.0 broke libvirt <7.2 add a breaks to avoid partial upgrade issues (LP: #1932264)
With qemu 6.0 you'll see issues with hotplug on attach-device (there are more
cases than the examples show)

virsh -c qemu:///system attach-device impish-2nd-hotplug hotplug-rng.xml
error: Failed to attach device from hotplug-rng.xml
error: internal error: unable to execute QEMU command
  'object-add': Parameter 'props' is unexpected

virsh -c qemu:///system attach-device impish-2nd-hotplug hotplug-mem64.xml
error: Failed to attach device from hotplug-mem64.xml
error: internal error: unable to execute QEMU command
  'object-add': Parameter 'size' is missing

This is due to qemu
https://git.qemu.org/?p=qemu.git;a=commit;h=50243407457a
It was reported and discussed in
https://bugzilla.redhat.com/show_bug.cgi?id=1944985
It is intentional and will stay that way, so higher layers need to adapt.
https://libvirt.org/git/?p=libvirt.git;a=commit;h=e0eeb2cc67d9
https://libvirt.org/git/?p=libvirt.git;a=commit;h=96850dfe216f
https://libvirt.org/git/?p=libvirt.git;a=commit;h=4f33b817b292

That means >=7.2 is needed for qemu 6.0 and to avoid any potential
issues on e.g. partial upgrades adding a breaks in d/control will help.